package toopher_radius_config;
use strict;

{
  my $toopher_config = 
  {
    toopher_api => {  
      # These values control how your server connects to the Toopher API
      url   =>  'https://api.toopher.com/v1/',
      key   =>  'YOUR TOOPHER API KEY', 
      secret=>  'YOUR TOOPHER API SECRET',
      poll_timeout => 30,
      },
    terminal_identifier => (
      # if your VPN provider implements custom RADIUS attributes that
      # can be used to uniquely identify the client terminal, you
      # can list them here to take advantage of Toopher Automation.
      # If this list is empty, automation will be disabled.
      # Note that Calling-Station-Id (or any other attribute
      # reporting the user's IP address) is not considered
      # a secure terminal identifier when used alone, though it
      # may be used in combination with other keys.
    ),
    prompts => {
      pairing_challenge => 'Toopher 2-factor authentication is enabled for your account.  Please enter the pairing phrase generated by the Toopher mobile app:',
      otp_challenge => 'Timeout while contacting the Toopher API.  Please enter the OTP generated by the Toopher Mobile App to proceed.'
      },
    ldap => {
      # [Deprecated] Connection to the back-end LDAP server for username/password authentication,
      # as well as storage of Toopher-specific user attributes.
      username =>  'toopher_radius',
      password =>  'p@ssw0rd',
      host  =>     '127.0.0.1',
      principal => 'example.toopher.com',
      dc        => 'DC=example,DC=toopher,DC=com',
      },
  };
  sub get_config { return $toopher_config; }
}
